Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-07, with the labels that each got.

#409 Update flowchart image and description
  CHANGELOG.md
  docs/Overview.rst
  docs/images/MVS_flowchart.png
Labels: documentation

#417 add a section to the autoreport to display logging messages like warnings and errors
  CHANGELOG.md
  report/assets/styles.css
  src/F2_autoreport.py
  tests/inputs/csv_elements/energyConsumption.csv
  tests/inputs/csv_elements/simulation_settings.csv
Labels: enhancement

#452 Update/to oemof 0.4.x - Continued work
  requirements.txt
  setup.py
  src/D0_modelling_and_optimization.py
  src/E0_evaluation.py
  src/E1_process_results.py
Labels: enhancement

#453 Fix/lcoe asset not shown
  CHANGELOG.md
  src/E0_evaluation.py
  src/E1_process_results.py
  src/E2_economics.py
  src/F0_output.py
  src/F2_autoreport.py
  src/constants_json_strings.py
  src/constants_output.py
  tests/test_E0_evaluation.py
  tests/test_E2_economics.py
  tests/test_F0_output.py
Labels: enhancement

#456 Feature/add parser arguments
  CHANGELOG.md
  docs/Developing.rst
  docs/tables/table_tests.csv
  src/A0_initialization.py
  tests/test_A0_initialization.py
  tests/test_B0_data_input_json.py
  tests/test_E0_evaluation.py
  tests/test_F0_output.py
  tests/test_F1_plotting.py
  tests/test_benchmark_simple_scenarios.py
Labels: enhancement

#379 Defining more constants and deleting a function
  CHANGELOG.md
  docs/troubleshooting.rst
  src/C0_data_processing.py
  src/D1_model_components.py
  src/E2_economics.py
  src/E3_indicator_calculation.py
  src/F0_output.py
  src/constants.py
  src/constants_json_strings.py
  tests/test_A1_csv_to_json.py
  tests/test_C0_data_processing.py
  tests/test_sensitivity.py
Labels: bug

#468 Add None rounding in E0
  CHANGELOG.md
  src/E0_evaluation.py
  tests/test_E0_evaluation.py
  tests/test_F1_plotting.py
Labels: bug

#473 Enable report compilation using `-pdf` on Windows
  CHANGELOG.md
  requirements.txt
  src/F2_autoreport.py
  tests/test_A0_initialization.py
Labels: bug

#480 Remove extensive pyppeteer console messages
  src/F2_autoreport.py
Labels: enhancement

#439 Make plots from the results using Plotly and embed them in the auto-report
  CHANGELOG.md
  report/assets/styles.css
  requirements.txt
  src/F2_autoreport.py
  src/constants.py
Labels: enhancement

#472 Fix FileExistsError in pytest
  CHANGELOG.md
  src/A0_initialization.py
  tests/test_A0_initialization.py
  tests/test_utils.py
Labels: bug, enhancement

#483 Fix pytests for release
  CHANGELOG.md
  docs/MVS_parameters.rst
  mvs_eland_tool/local_deploy.py
  src/constants.py
  src/constants_json_strings.py
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/simulation_settings.csv
  tests/benchmark_test_inputs/rerun/mvs_config.json
  tests/inputs/csv_elements/simulation_settings.csv
  tests/inputs/mvs_config.json
  tests/test_benchmark_simple_scenarios.py
  tests/test_data/inputs_F1_plot_nx_false/csv_elements/simulation_settings.csv
  tests/test_data/inputs_F1_plot_nx_true/csv_elements/simulation_settings.csv
  tests/test_data/test_data_for_D0.json
  tests/test_data/test_json_for_E3.json
Labels: bug
