Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-11, with the labels that each got.

#622 Replace DSO sub-system image and fix typos in docs
  CHANGELOG.md
  docs/Developing.rst
  docs/E-Land_Requirements.rst
  docs/Installation.rst
  docs/MVS_Outputs.rst
  docs/References.rst
  docs/images/Model_Assumptions_energyProvider_assets.png
  docs/simulating_with_the_mvs.rst
  docs/troubleshooting.rst
Labels: documentation, enhancement

#623 Add log messages to results json file
  CHANGELOG.md
  src/multi_vector_simulator/E0_evaluation.py
  src/multi_vector_simulator/F0_output.py
  src/multi_vector_simulator/F1_plotting.py
  src/multi_vector_simulator/F2_autoreport.py
  src/multi_vector_simulator/utils/constants_json_strings.py
Labels: enhancement

#629 Small fix for RTD - Energy carrier weighting
  CHANGELOG.md
  docs/Model_Assumptions.rst
Labels: bug, enhancement

#643 Fix formatting and rendering issues in the autoreport
  CHANGELOG.md
  src/multi_vector_simulator/F2_autoreport.py
Labels: enhancement

#637 Renewable factor and renewable share of local generation
  CHANGELOG.md
  docs/MVS_Outputs.rst
  docs/MVS_parameters_list.csv
  docs/Model_Assumptions.rst
  input_template/csv_elements/constraints.csv
  src/multi_vector_simulator/D2_model_constraints.py
  src/multi_vector_simulator/E0_evaluation.py
  src/multi_vector_simulator/E3_indicator_calculation.py
  src/multi_vector_simulator/E4_verification.py
  src/multi_vector_simulator/utils/constants.py
  src/multi_vector_simulator/utils/constants_json_strings.py
  tests/benchmark_test_inputs/ABE_grid_PV_battery/csv_elements/constraints.csv
  tests/benchmark_test_inputs/AB_grid_PV/csv_elements/constraints.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/constraints.csv
  tests/benchmark_test_inputs/AE_grid_battery/csv_elements/constraints.csv
  tests/benchmark_test_inputs/AE_grid_battery_peak_pricing/csv_elements/constraints.csv
  tests/benchmark_test_inputs/AFG_grid_heatpump_heat/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_0/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_70/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/constraints.csv
  tests/benchmark_test_inputs/rerun/mvs_config.json
  tests/inputs/csv_elements/constraints.csv
  tests/inputs/mvs_config.json
  tests/test_E3_indicator_calculation.py
  tests/test_E4_verification.py
  tests/test_benchmark_KPI.py
  tests/test_benchmark_constraints.py
  tests/test_data/inputs_F1_plot_es_graph/csv_elements/constraints.csv
  tests/test_data/inputs_for_D0/mvs_config.json
  tests/test_data/inputs_for_D1/mvs_config.json
Labels: enhancement

#654 Temporary fix for demands section in the autoreport
  CHANGELOG.md
  src/multi_vector_simulator/E1_process_results.py
  src/multi_vector_simulator/F2_autoreport.py
Labels: enhancement

#665 Modify autoreport to display demands sector-wise
  CHANGELOG.md
  src/multi_vector_simulator/E1_process_results.py
  src/multi_vector_simulator/F1_plotting.py
  src/multi_vector_simulator/F2_autoreport.py
Labels: enhancement
