Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-10, with the labels that each got.

#542 Add benchmark tests for csv features
  CHANGELOG.md
  docs/files_to_be_displayed/example_scalar_as_timeseries_energyConversion.csv
  docs/simulating_with_the_mvs.rst
  src/mvs_eland/C0_data_processing.py
  src/mvs_eland/E2_economics.py
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/economic_data.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/energyConsumption.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/energyConversion.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/energyProduction.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/energyStorage.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/simulation_settings.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/time_series/demand.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/time_series/parameter_timeseries.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/economic_data.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/energyConsumption.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/energyConversion.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/energyProduction.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/energyStorage.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/simulation_settings.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/time_series/demand.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/time_series/parameter_timeseries.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/constraints.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/economic_data.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/energyConsumption.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/energyConversion.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/energyProduction.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/energyStorage.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/simulation_settings.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/time_series/demand.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/time_series/parameter_timeseries.csv
  tests/test_E2_economics.py
  tests/test_F0_output.py
  tests/test_benchmark_constraints.py
  tests/test_benchmark_special_features.py
Labels: enhancement

#479 Update the mvs parameters docs file
  CHANGELOG.md
  docs/MVS_parameters.rst
Labels: documentation, enhancement

#590 Add rtd file for requirements
  CHANGELOG.md
  docs/E-Land_Requirements.rst
  docs/index.rst
Labels: documentation

#597 Fix rtd for defining parameters as timeseries
  CHANGELOG.md
  docs/files_to_be_displayed/example_scalar_as_timeseries_energyConversion.csv
  docs/simulating_with_the_mvs.rst
Labels: documentation

#604 Fix math equations in readthedocs
  CHANGELOG.md
  docs/MVS_Outputs.rst
  docs/Model_Assumptions.rst
Labels: documentation

#618 Fix broken links to input CSV files in readthedocs
  CHANGELOG.md
  docs/simulating_with_the_mvs.rst
Labels: bug, documentation

#619 Improve the documentation section on assigning weights to the carriers
  CHANGELOG.md
  docs/Model_Assumptions.rst
Labels: documentation, enhancement

#621 Add values of energy carrier weights
  CHANGELOG.md
  docs/Model_Assumptions.rst
  src/multi_vector_simulator/utils/constants.py
Labels: enhancement

#609 add KPI's
  CHANGELOG.md
  docs/MVS_Outputs.rst
Labels: documentation, enhancement
