Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-03, with the labels that each got.

#138 Integrating tests for A0
  .gitignore
  CHANGELOG.md
  docs/MVS_parameters.rst
  inputs/csv_elements/economic_data.csv
  inputs/csv_elements/energyConsumption.csv
  inputs/csv_elements/energyConversion.csv
  inputs/csv_elements/energyProduction.csv
  inputs/csv_elements/energyProviders.csv
  inputs/csv_elements/energyStorage.csv
  inputs/csv_elements/fixcost.csv
  inputs/csv_elements/project_data.csv
  inputs/csv_elements/simulation_settings.csv
  inputs/csv_elements/storage_01.csv
  inputs/elements/working_example2.json
  inputs/mvs_config.json
  inputs/time_series/demand_habor.csv
  inputs/time_series/demand_remaining.csv
  inputs/time_series/demand_shore_power.csv
  inputs/time_series/industrial_process_heat.csv
  inputs/time_series/pv_gen_merra2_2014_eff1_tilt40_az180.csv
  mvs_eland_tool/mvs_eland_tool.py
  src/A0_initialization.py
  src/A1_csv_to_json.py
  src/B0_data_input_json.py
  src/C0_data_processing.py
  src/C1_verification.py
  src/constants.py
  tests/constants.py
  tests/inputs/csv_elements/economic_data.csv
  tests/inputs/csv_elements/energyConsumption.csv
  tests/inputs/csv_elements/energyConversion.csv
  tests/inputs/csv_elements/energyProduction.csv
  tests/inputs/csv_elements/energyProviders.csv
  tests/inputs/csv_elements/energyStorage.csv
  tests/inputs/csv_elements/fixcost.csv
  tests/inputs/csv_elements/project_data.csv
  tests/inputs/csv_elements/simulation_settings.csv
  tests/inputs/csv_elements/storage_01.csv
  tests/inputs/mvs_config.json
  tests/test_A0_initialization.py
  tests/test_A1_csv_to_json.py
Labels: enhancement

#181 Bugfix/value as timeseries
  inputs/csv_elements/simulation_settings.csv
  inputs/mvs_config.json
  src/A1_csv_to_json.py
  src/C0_data_processing.py
Labels: bug

#183 Bugfix/boolean settings
  CHANGELOG.md
  inputs/mvs_config.json
  src/D0_modelling_and_optimization.py
Labels: bug

#187 Bugfix/aggregation of demand across vectors
  CHANGELOG.md
  src/E0_evaluation.py
  src/F0_output.py
  src/F1_plotting.py
Labels: bug

#190 Bugfix/optimized storage
  CHANGELOG.md
  inputs/csv_elements/simulation_settings.csv
  src/D0_modelling_and_optimization.py
Labels: bug

#192 Fix the calculation of optimizedAddCap
  src/E1_process_results.py
Labels: bug

#199 Add pull request template
  .github/pull_request_template.md
  CHANGELOG.md
Labels: enhancement

#203 Fix json file
  inputs/mvs_config.json
Labels: bug

#202 Improve shore power randomization.
  CHANGELOG.md
  src/A0_initialization.py
  src/standalone_custom/shore_power_randomize.py
  src/standalone_custom/test_shore_power_randomize.py
Labels: enhancement

#210 Fix searching for dict key "input_bus_name"
  src/E1_process_results.py
Labels: bug

#209 Bug fix TypeError
  inputs/mvs_config.json
Labels: bug

#221 Adding Troubleshooting to docs (pygraphviz, xlrd, JSONDecodeError)
  CHANGELOG.md
  docs/index.rst
  docs/troubleshooting.rst
Labels: documentation

#225 Update pull_request_template.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: enhancement
