Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-08, with the labels that each got.

#454 Introducing excess sink for each bus and reworking DSOs
  CHANGELOG.md
  docs/Code.rst
  docs/Model_Assumptions.rst
  docs/images/Model_Assumptions_Peak_Demand_Pricing_Dispatch_Graph.png
  docs/images/Model_Assumptions_energyProvider_assets.png
  docs/index.rst
  input_template/csv_elements/energyProviders.csv
  src/A1_csv_to_json.py
  src/C0_data_processing.py
  src/D1_model_components.py
  src/E0_evaluation.py
  src/E3_indicator_calculation.py
  src/F1_plotting.py
  src/F2_autoreport.py
  src/constants.py
  src/constants_json_strings.py
  tests/benchmark_test_inputs/ABE_grid_PV_battery/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/AB_grid_PV/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/AE_grid_battery/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/rerun/mvs_config.json
  tests/inputs/csv_elements/energyConversion.csv
  tests/inputs/csv_elements/energyProduction.csv
  tests/inputs/csv_elements/energyProviders.csv
  tests/inputs/csv_elements/simulation_settings.csv
  tests/inputs/mvs_config.json
  tests/test_C0_data_processing.py
  tests/test_E3_indicator_calculation.py
  tests/test_benchmark_simple_scenarios.py
  tests/test_data/inputs_F1_plot_nx_false/csv_elements/energyProviders.csv
  tests/test_data/inputs_F1_plot_nx_true/csv_elements/energyProviders.csv
  tests/test_data/test_data_for_D0.json
  tests/test_data/test_data_for_D1.json
  tests/test_data/test_json_for_E3.json
Labels: enhancement

#493 Fix NaN issue
  CHANGELOG.md
  src/E2_economics.py
  src/F2_autoreport.py
Labels: bug, enhancement

#482 Create pie-charts using Plotly
  CHANGELOG.md
  src/E2_economics.py
  src/F2_autoreport.py
  tests/inputs/csv_elements/storage_01.csv
Labels: enhancement

#495 Disaggregate C0 and add some tests
  CHANGELOG.md
  src/C0_data_processing.py
  src/C2_economic_functions.py
  tests/test_C0_data_processing.py
  tests/test_C2_economic_functions.py
Labels: enhancement

#499 Save plots created by F2 to disk
  CHANGELOG.md
  src/F2_autoreport.py
Labels: enhancement

#505 Reformat doc-strings in F2 Module
  CHANGELOG.md
  src/F2_autoreport.py
Labels: documentation

#492 Definition of fuel sources
  CHANGELOG.md
  docs/Model_Assumptions.rst
  src/A1_csv_to_json.py
  src/C0_data_processing.py
  src/C1_verification.py
  src/E1_process_results.py
  src/constants_json_strings.py
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/energyConversion.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/energyProduction.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/energyProviders.csv
  tests/inputs/csv_elements/energyProduction.csv
  tests/test_A1_csv_to_json.py
  tests/test_benchmark_simple_scenarios.py
Labels: enhancement

#520 Disaggregate and test economic postprocessing (E2)
  CHANGELOG.md
  mvs_report.py
  src/C0_data_processing.py
  src/C2_economic_functions.py
  src/D0_modelling_and_optimization.py
  src/E1_process_results.py
  src/E2_economics.py
  src/F1_plotting.py
  src/F2_autoreport.py
  src/constants.py
  src/constants_json_strings.py
  src/constants_output.py
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/economic_data.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/energyConsumption.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/energyConversion.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/energyProduction.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/energyStorage.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/simulation_settings.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/storage_1.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/test_data_economic_expected_values.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/test_data_economic_expected_values.xls
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/time_series/demand.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/time_series/pv_solar_input.csv
  tests/test_C0_data_processing.py
  tests/test_C2_economic_functions.py
  tests/test_D0_modelling_and_optimization.py
  tests/test_E2_economics.py
  tests/test_benchmark_KPI.py
  tests/test_benchmark_simple_scenarios.py
Labels: bug

#534 Fix report generation for multiple sectors
  CHANGELOG.md
  src/A1_csv_to_json.py
  src/F2_autoreport.py
Labels: bug

#525 Add system-wide KPI to evaluation
  CHANGELOG.md
  docs/References.rst
  docs/index.rst
  src/A0_initialization.py
  src/C0_data_processing.py
  src/C2_economic_functions.py
  src/E0_evaluation.py
  src/E1_process_results.py
  src/E2_economics.py
  src/E3_indicator_calculation.py
  src/F0_output.py
  src/F1_plotting.py
  src/F2_autoreport.py
  src/constants.py
  src/constants_json_strings.py
  src/constants_output.py
  tests/test_C2_economic_functions.py
  tests/test_E2_economics.py
  tests/test_E3_indicator_calculation.py
  tests/test_data/test_json_for_E3.json
Labels: enhancement
