Repository rl-institut/multi-vector-simulator, pull requests merged in 2020-12, with the labels that each got.

#684 Fix/plots issue 444 review
  CHANGELOG.md
  tests/inputs/csv_elements/economic_data.csv
  tests/inputs/csv_elements/energyConversion.csv
  tests/inputs/csv_elements/energyProviders.csv
  tests/inputs/csv_elements/storage_01.csv
  tests/test_A0_initialization.py
  tests/test_A1_csv_to_json.py
  tests/test_B0_data_input_json.py
  tests/test_E0_evaluation.py
  tests/test_E1_process_results.py
Labels: bug

#613 Write benchmark tests for npc and lcoe
  CHANGELOG.md
  src/multi_vector_simulator/utils/constants_output.py
  tests/benchmark_test_inputs/AB_grid_PV/csv_elements/energyProviders.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/test_data_economic_expected_values.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/test_data_economic_expected_values.xls
  tests/test_benchmark_KPI.py
Labels: enhancement

#678 Include energyBusses.csv in RTD
  CHANGELOG.md
  docs/simulating_with_the_mvs.rst
Labels: documentation

#697 Update with CO2 emission factors
  CHANGELOG.md
  docs/Model_Assumptions.rst
Labels: documentation

#646 Insert the instructions into the readme from rst file
  CHANGELOG.md
  README.md
  README.rst
  docs/Installation.rst
  setup.py
  src/multi_vector_simulator/A0_initialization.py
  src/multi_vector_simulator/B0_data_input_json.py
  src/multi_vector_simulator/C1_verification.py
  src/multi_vector_simulator/E0_evaluation.py
Labels: documentation, enhancement

#725 Disable the logging of imported and third-party libraries
  CHANGELOG.md
  docs/conf.py
  src/multi_vector_simulator/A0_initialization.py
Labels: enhancement
