Repository rl-institut/multi-vector-simulator, pull requests merged in 2021-03, with the labels that each got.

#810 Fix EPA-MVS-parser
  CHANGELOG.md
  src/multi_vector_simulator/C0_data_processing.py
  src/multi_vector_simulator/utils/__init__.py
  src/multi_vector_simulator/utils/data_parser.py
Labels: bug

#795 Add fix project cost feature to MVS and clean up A1
  CHANGELOG.md
  docs/Model_Assumptions.rst
  docs/Model_Equations.rst
  input_template/csv_elements/fixcost.csv
  src/multi_vector_simulator/A1_csv_to_json.py
  src/multi_vector_simulator/C0_data_processing.py
  src/multi_vector_simulator/E0_evaluation.py
  src/multi_vector_simulator/E1_process_results.py
  src/multi_vector_simulator/utils/constants.py
  src/multi_vector_simulator/utils/exceptions.py
  tests/benchmark_test_inputs/ABE_grid_PV_battery/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/AB_grid_PV/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/AE_grid_battery/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/AE_grid_battery_peak_pricing/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/AFG_grid_heatpump_heat/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_None/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_low/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_low_grid_RE_100/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_0/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_70/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feature_stratified_thermal_storage/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feedin_dispatch/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/Feedin_optimize/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/constraint_degree_of_autonomy_0/csv_elements/fixcost.csv
  tests/benchmark_test_inputs/constraint_degree_of_autonomy_70/csv_elements/fixcost.csv
  tests/inputs/csv_elements/fixcost.csv
  tests/inputs/csv_elements/simulation_settings.csv
  tests/inputs/mvs_config.json
  tests/test_A1_csv_to_json.py
  tests/test_C0_data_processing.py
  tests/test_E1_process_results.py
  tests/test_data/inputs_for_D0/mvs_config.json
  tests/test_data/inputs_for_D1/mvs_config.json
Labels: documentation, enhancement

#804 Component models section RTD - info on each required asset
  CHANGELOG.md
  docs/Model_Assumptions.rst
  docs/simulating_with_the_mvs.rst
Labels: documentation
