Repository rl-institut/multi-vector-simulator, pull requests merged in 2021-01, with the labels that each got.

#739 Function to check for abnormal SOC values
  CHANGELOG.md
  src/multi_vector_simulator/D0_modelling_and_optimization.py
  src/multi_vector_simulator/E0_evaluation.py
  src/multi_vector_simulator/E1_process_results.py
  src/multi_vector_simulator/E4_verification.py
  src/multi_vector_simulator/utils/constants_json_strings.py
  tests/test_E4_verification.py
Labels: enhancement

#722 Create a new parameter for scenario description
  CHANGELOG.md
  docs/MVS_parameters.rst
  docs/MVS_parameters_list.csv
  docs/conf.py
  input_template/csv_elements/project_data.csv
  src/multi_vector_simulator/F2_autoreport.py
  src/multi_vector_simulator/utils/constants.py
  src/multi_vector_simulator/utils/constants_json_strings.py
  tests/benchmark_test_inputs/ABE_grid_PV_battery/csv_elements/project_data.csv
  tests/benchmark_test_inputs/AB_grid_PV/csv_elements/project_data.csv
  tests/benchmark_test_inputs/AD_grid_diesel/csv_elements/project_data.csv
  tests/benchmark_test_inputs/AE_grid_battery/csv_elements/project_data.csv
  tests/benchmark_test_inputs/AE_grid_battery_peak_pricing/csv_elements/project_data.csv
  tests/benchmark_test_inputs/AFG_grid_heatpump_heat/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_None/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_low/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Constraint_maximum_emissions_low_grid_RE_100/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_0/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Constraint_minimal_renewable_share_70/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Economic_KPI_C2_E2/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_input_flows_as_list/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_output_flows_as_list/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feedin_dispatch/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feedin_optimize/csv_elements/project_data.csv
  tests/benchmark_test_inputs/rerun/mvs_config.json
  tests/inputs/csv_elements/project_data.csv
  tests/inputs/mvs_config.json
  tests/test_data/inputs_for_D0/mvs_config.json
  tests/test_data/inputs_for_D1/mvs_config.json
  tests/test_data/inputs_for_E1/csv_elements/project_data.csv
Labels: enhancement

#753 Add a section in RTD describing the E4 verification tests
  CHANGELOG.md
  docs/Model_Assumptions.rst
Labels: documentation, enhancement

#746 Set nans to zero
  CHANGELOG.md
  docs/Model_Assumptions.rst
  src/multi_vector_simulator/C0_data_processing.py
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/csv_elements/project_data.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/time_series/demand.csv
  tests/benchmark_test_inputs/Feature_parameters_as_timeseries/time_series/parameter_timeseries.csv
  tests/test_C0_data_processing.py
  tests/test_benchmark_special_features.py
Labels: bug

#754 Give user helpful error messages when simulation terminates unsuccessfully
  CHANGELOG.md
  src/multi_vector_simulator/D0_modelling_and_optimization.py
  src/multi_vector_simulator/utils/exceptions.py
  tests/test_D0_modelling_and_optimization.py
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/constraints.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/economic_data.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyBusses.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyConsumption.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyConversion.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyProduction.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyProviders.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/energyStorage.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/fixcost.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/project_data.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/csv_elements/simulation_settings.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/time_series/demand.csv
  tests/test_data/known_oemof_errors/insufficient_capacity/time_series/pv_solar_input.csv
Labels: enhancement
